#!/usr/bin/env bash

STARTUP_SCRIPT=startup.gdb

ver=`gdb --version | head -n 1| sed -r 's/GNU gdb \(GDB\) ([[:digit:]]+).([[:digit:]]+)/\1 \2/'`
major=`echo $ver | awk '{print $1}'`
minor=`echo $ver | awk '{print $2}'`

err="gdb version should be >= 7.12, but your gdb is $major,$minor"

if [ "$major" -lt "7" ]; then
  echo $err
  exit 1
fi

if [[ "$major" -eq "7" && "$minor" -lt "12" ]]; then
  echo $err
  exit 1
fi


gdb $@ -x $STARTUP_SCRIPT