windows=['src', 'aux']

journal=[{'action_num': 1,
  'name': 'gdb',
  'stream': 'file main\nb f2\nrun'},
 {'action_num': 4,
  'name': 'gdb',
  'stream': 'frame 2'},
 {'action_num': 5,
  'name': 'gdb',
  'stream': 'frame 1'},
 {'action_num': 6,
  'name': 'gdb',
  'stream': 'frame 0'},
 {'action_num': 7,
  'name': 'gdb',
  'stream': 'up'},
 {'action_num': 8,
  'name': 'gdb',
  'stream': 'up'},
 {'action_num': 9,
  'name': 'gdb',
  'stream': 'down'},
 {'action_num': 10,
  'name': 'gdb',
  'stream': 'down'},
 {'action_num': 11,
  'name': 'gdb',
  'stream': 'up'},
 {'action_num': 12,
  'name': 'aux',
  'stream': '\x1b[<0;49;3M\x1b[<0;49;3m'},
 {'action_num': 13,
  'name': 'gdb',
  'stream': 'up'},
 {'action_num': 14,
  'name': 'gdb',
  'stream': 'up'},
 {'action_num': 15,
  'name': 'aux',
  'stream': '\x1b[<0;54;5M\x1b[<0;54;5m'},
 {'action_num': 16,
  'name': 'aux',
  'stream': '\x1b[<0;54;3M\x1b[<0;54;3m'},
 {'action_num': 17,
  'name': 'aux',
  'stream': '\x1b[<0;61;7M\x1b[<0;61;7m'},
 {'action_num': 18,
  'name': 'gdb',
  'stream': 'down'},
 {'action_num': 19,
  'name': 'gdb',
  'stream': 'down'},
 {'action_num': 20,
  'name': 'aux',
  'stream': '\x1b[<0;57;5M\x1b[<0;57;5m'},
 {'action_num': 21,
  'name': 'aux',
  'stream': '\x1b[<0;54;8M\x1b[<0;54;8m'}]

